# Generated by Django 2.2 on 2020-04-21 20:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
