# Generated by Django 3.0.4 on 2020-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
